### ISSUE TITLE
Type annotations / type hints / stub files for mypy

### ISSUE THREAD

**Issue by MartinThoma** [RomeoDespres/pkce#1]
Are there plans to add type annotations or stub files for mypy?

I've written an [article about type annotations](https://medium.com/analytics-vidhya/type-annotations-in-python-3-8-3b401384403d) if you need one :-)

**Comment by RomeoDespres** [comment]
Hi @MartinThoma, thanks to @jpmolinamatute this has been added today! The addition is now live on PyPI :)

**Comment by RomeoDespres** [comment]
Sorry there's a bug in the release, it will be fixed soon but doesn't work quite yet!
